# Generated by Django 4.1 on 2023-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Coading', 'Coading'), ('Sports', 'Sports'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel')], default='Coding', max_length=250),
        ),
    ]
